"use client";

import { useState } from "react";

import type { LocationChart } from "@/lib/api";
import { titleCase } from "@/features/scouting/domain";

const COLORS = ["#37a7ff", "#ff9418", "#74c82b", "#f45555", "#a57aff", "#3fd0b2", "#f1d45d", "#d7dde0"];

function Shape({ index, cx, cy, size, fill }: { index: number; cx: number; cy: number; size: number; fill: string }) {
  const points = index % 6 === 2 ? `${cx},${cy-size} ${cx+size},${cy+size} ${cx-size},${cy+size}`
    : index % 6 === 3 ? `${cx},${cy-size} ${cx+size},${cy} ${cx},${cy+size} ${cx-size},${cy}`
    : index % 6 === 4 ? `${cx-size},${cy-size} ${cx+size},${cy-size} ${cx},${cy+size}`
    : `${cx-size},${cy} ${cx-size/2},${cy-size*.86} ${cx+size/2},${cy-size*.86} ${cx+size},${cy} ${cx+size/2},${cy+size*.86} ${cx-size/2},${cy+size*.86}`;
  if (index % 6 === 0) return <circle className="pitch-symbol" cx={cx} cy={cy} r={size} fill={fill}/>;
  if (index % 6 === 1) return <rect className="pitch-symbol" x={cx-size} y={cy-size} width={size*2} height={size*2} fill={fill}/>;
  return <polygon className="pitch-symbol" points={points} fill={fill}/>;
}

/** Interactive catcher-view pitch chart. Encodings are generated by the verified backend chart tool. */
export function StrikeZone({ chart, compact = false }: { chart: LocationChart; compact?: boolean }) {
  const [hidden, setHidden] = useState<string[]>([]);
  const left = 54, top = 24, width = 442, height = 354;
  const plotted = chart.points.filter(point => Number.isFinite(point.plate_x) && Number.isFinite(point.plate_z));
  const xMin = Math.min(-2.5, Math.floor(Math.min(...plotted.map(point => point.plate_x)) * 2) / 2);
  const xMax = Math.max(2.5, Math.ceil(Math.max(...plotted.map(point => point.plate_x)) * 2) / 2);
  const zMin = Math.min(0, Math.floor(Math.min(...plotted.map(point => point.plate_z)) * 2) / 2);
  const zMax = Math.max(5, Math.ceil(Math.max(...plotted.map(point => point.plate_z)) * 2) / 2);
  const x = (value: number) => left + (value - xMin) / (xMax - xMin) * width;
  const y = (value: number) => top + (zMax - value) / (zMax - zMin) * height;
  const ticks = (min: number, max: number) => Array.from({length: 6}, (_, index) => min + (max - min) * index / 5);
  const value = (point: LocationChart["points"][number], feature: string) => point.features.find(item => item.name === feature)?.value ?? "Unclassified";
  const categories = (feature: string) => [...new Set(plotted.map(point => value(point, feature)))];
  const colorEncoding = chart.encodings.find(item => item.channel === "color");
  const shapeEncoding = chart.encodings.find(item => item.channel === "shape");
  const key = (feature: string, category: string) => `${feature}:${category}`;
  const visible = (point: LocationChart["points"][number]) => !chart.encodings.some(encoding => hidden.includes(key(encoding.feature, value(point, encoding.feature))));
  function toggle(feature: string, category: string) {
    const item = key(feature, category);
    setHidden(items => items.includes(item) ? items.filter(current => current !== item) : [...items, item]);
  }
  return <section className={`strike-chart ${compact ? "compact" : ""}`}>
    {!compact && <div className="strike-chart-head"><div><span>LOCATION MAP / CATCHER VIEW</span><h3>{chart.title}</h3></div><small>{plotted.length} plotted pitches</small></div>}
    <svg className="strike-zone" viewBox="0 0 520 430" role="img" aria-label={`${chart.title}. ${plotted.length} pitch locations.`}>
      <title>{chart.title}</title><rect className="zone-frame" x={left} y={top} width={width} height={height}/>
      {ticks(zMin, zMax).map(tick => <g className="zone-axis" key={`y-${tick}`}><line x1={left} x2={left+width} y1={y(tick)} y2={y(tick)}/>{!compact && <text x={left-10} y={y(tick)+4} textAnchor="end">{tick.toFixed(tick % 1 ? 1 : 0)}</text>}</g>)}
      {ticks(xMin, xMax).map(tick => <g className="zone-axis" key={`x-${tick}`}><line x1={x(tick)} x2={x(tick)} y1={top} y2={top+height}/>{!compact && <text x={x(tick)} y={top+height+20} textAnchor="middle">{tick.toFixed(tick % 1 ? 1 : 0)}</text>}</g>)}
      <rect className="zone-box" x={x(-.83)} y={y(3.5)} width={x(.83)-x(-.83)} height={y(1.5)-y(3.5)}/>
      {[-.277,.277].map(item => <line className="zone-cell" key={`zx-${item}`} x1={x(item)} x2={x(item)} y1={y(3.5)} y2={y(1.5)}/>)}
      {[2.167,2.833].map(item => <line className="zone-cell" key={`zy-${item}`} x1={x(-.83)} x2={x(.83)} y1={y(item)} y2={y(item)}/>)}
      <path className="home-plate" d={`M ${x(-.38)} ${y(.3)} L ${x(.38)} ${y(.3)} L ${x(.48)} ${y(.12)} L ${x(0)} ${y(0)} L ${x(-.48)} ${y(.12)} Z`}/>
      {plotted.filter(visible).map((point, index) => {
        const colorValues = colorEncoding ? categories(colorEncoding.feature) : [];
        const shapeValues = shapeEncoding ? categories(shapeEncoding.feature) : [];
        const color = colorEncoding ? COLORS[colorValues.indexOf(value(point, colorEncoding.feature)) % COLORS.length] : COLORS[0];
        const shape = shapeEncoding ? shapeValues.indexOf(value(point, shapeEncoding.feature)) : 0;
        return <g className="pitch-mark" key={index}><title>{point.features.map(item => `${titleCase(item.name)}: ${item.value}`).join(" · ")}</title><Shape index={shape} cx={x(point.plate_x)} cy={y(point.plate_z)} size={compact ? 5.5 : 4.5} fill={color}/></g>;
      })}
      {!compact && <><text className="axis-label" x={left+width/2} y="425" textAnchor="middle">Horizontal plate location (ft)</text><text className="axis-label" transform={`translate(14 ${top+height/2}) rotate(-90)`} textAnchor="middle">Height (ft)</text></>}
    </svg>
    {!compact && chart.encodings.map(encoding => <div className="zone-legend" key={`${encoding.channel}-${encoding.feature}`}>
      <span>{encoding.label || titleCase(encoding.feature)} · {encoding.channel}</span>
      {categories(encoding.feature).map((category, index) => <button type="button" aria-pressed={!hidden.includes(key(encoding.feature, category))} key={category} onClick={() => toggle(encoding.feature, category)}>
        {encoding.channel === "color" ? <i style={{background:COLORS[index % COLORS.length]}}/> : <svg viewBox="0 0 14 14" aria-hidden="true"><Shape index={index} cx={7} cy={7} size={4} fill="#c3cac3"/></svg>}{category}
      </button>)}
    </div>)}
  </section>;
}
